# Generated by Django 4.0.3 on 2023-09-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cookingheavenuser_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookingheavenuser',
            old_name='active',
            new_name='is_active',
        ),
    ]
