version: '3.4'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web_nw
    depends_on:
      - postgres

  postgres:    
    image: postgres
    restart: always
    networks:
      - web_nw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1123QwER
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

networks:
  web_nw:
    driver: bridge
