# Generated by Django 4.0.3 on 2022-03-19 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="course",
        ),
    ]
