# Generated by Django 4.0.3 on 2022-03-21 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_remove_recipe_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="recipe_likes_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="types",
            field=models.ManyToManyField(blank=True, null=True, to="main.foodtype"),
        ),
    ]
