# Generated by Django 4.0.3 on 2022-04-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_recipe_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodType',
            new_name='Category',
        ),
    ]
