# Generated by Django 4.0.3 on 2022-04-10 19:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='recipe'),
        ),
    ]
