# Generated by Django 4.0.3 on 2022-04-14 19:58

import CookingHeaven.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[CookingHeaven.common.validators.is_alpha_and_space]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, validators=[CookingHeaven.common.validators.is_alpha_and_space]),
        ),
    ]
