# Generated by Django 4.0.3 on 2023-07-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_comment_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
